version: "3.7"

services:
  php:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: base
    pull_policy: always
    volumes:
      - .:/app
      - /home/richard/Development/PlotBox/dea-web:/app/testing
