version: "3.7"

services:
  php:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: main
    pull_policy: always
    volumes:
      - .:/app
